jwt:
  key:
    path: classpath
    name-private: app.key
    name-public: app.pub

aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  region: ${AWS_REGION}
  s3BucketName: ${AWS_S3_BUCKET_NAME}
  secretAccessKey: ${AWS_SECRET_ACCESS_KEY}

springdoc:
  swagger-ui:
    path: /docs

spring:
  profiles:
    active:
      - ${SPRING_PROFILES_ACTIVE_ENVIRONMENT}
  data:
    web:
      pageable:
        one-indexed-parameters: true
  flyway:
    baseline-on-migrate: true
    locations: "classpath:/migration/postgres,classpath:/migration/afterMigrate"
  jackson:
    deserialization:
      fail-on-unknown-properties: true # Se receber atributo desconhecido o spring retornara um erro
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB